# LOGGING
logging:
   level:
      com.lollipop:DEBUG

spring:
  datasource:
    schema: import.sql
    url: jdbc:mysql://127.0.0.1:3306/jike_exam?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql123

     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  http:
     encoding.charset: UTF-8
     encoding.enable: true
     encoding.force: true

  server:
     port: 8080
     address: localhost

  mvc:
      view:
          prefix: /templates/
          suffix: .ftl

  freemarker:
      cache: false
      request-context-attribute: request


# MyBatis
mybatis:
   typeAliasesPackage: com.lollipop.**.model
   mapperLocations: classpath:/com/lollipop/**/mapper/*.xml
   configLocation: classpath:/mybatis-config.xml

